### ISSUE TITLE
Support for Zweckform 4737

### ISSUE THREAD

**Issue by airblade** [druewilding/pdf_label_maker#1]
I'd love to see support for the Zweckform 4737 label.  I would add it myself but I just cannot find the layout details for the label anywhere online.  All I know is it's 63.5mm x 29.6mm and you have three per row.

What's the best way to get hold of the information to add support for this label to the code?

**Comment by druewilding** [comment]
Hi! I would love to add it for you. Do you have a sheet handy that you could measure? If you can, it's fairly easy to get the values in millimeters and add them in.

I found this page which i thought might help, but i can't decipher the numbers!
http://www.red-bean.com/labelnation/label-dimensions.html

Be aware that pdf-maker gem is quite out of date and it might be better (and easier) to rewrite this to use Prawn instead.

**Comment by airblade** [comment]
I found that page too, and was also baffled by the numbers!

Unfortunately I don't have a handy sheet.  I'll pop down to Rymans/Staples tomorrow and see if they have it in stock.

I can't believe that the label companies don't put this information online.  It's crazy to have to measure up their labels yourself.

**Comment by druewilding** [comment]
yeah i'm afraid i don't know of any way to do it apart from getting a ruler and measuring it yourself.

I suspect the information probably is online in some obscure place, but it's hard to find without being swamped with companies selling the labels!

if i get chance i'll also have a look in the local stationary shops.

**Comment by druewilding** [comment]
ooo, look what i found!
http://twitpic.com/yya9s

i think we might be able to work it out to this, thanks to openoffice! :)

**Comment by airblade** [comment]
Nice!

**Comment by druewilding** [comment]
Hi, i've pushed up a reasonable guess at what might be needed. It certainly looks nicely laid out, but the only way to really test it is to try printing on some real labels.

Fetch the latest and call it with 

```
    pdf = PdfLabelMaker.avery_labels(your_data, 'Zweckform4737')
```

If you need to tweak any of the variables, let me know and i'll update it in the repository.

aimee

**Comment by airblade** [comment]
That's great -- thank you very much!

I'll buy the labels tomorrow, give it a whirl, and let you know how I get on.

**Comment by druewilding** [comment]
Hey there! Any luck with the Zweckform labels?

**Comment by airblade** [comment]
I spent my lunchtime searching high and low around High Wycombe for the labels but couldn't find any.  I think I'll have to order some online.  So it might be a few days before I can give you an answer...
